---
title: "Load and save data"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r load_libraries, echo=FALSE, message=FALSE}
  if (!require("pacman")) install.packages("pacman")
  pacman::p_load(tidyverse, knitr, forcats)
```

```{r global_options, include=FALSE}
  knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE)
```

# load functions

```{r}
  source("../scripts/load_data.R")
```

# load & save beia gambia data

```{r}
  beia_gambia_baseline <- load_draeger_data(file_path = "../data/BEIA Gambia/Baseline/Raw Files",
                                            file_pattern = "[0-9].txt",
                                            pattern_1 = ".*-",
                                            pattern_2 = "_.*")
```

```{r}
  beia_gambia_followup <- load_draeger_data(file_path = "../data/BEIA Gambia/Follow up",
                                            file_pattern = "[0-9].txt",
                                            pattern_1 = ".*-",
                                            pattern_2 = "_.*")
```

# load & save beia south africa data

```{r}
  beia_south_africa <- load_draeger_data(file_path = "../data/BEIA South Africa/CO/Baseline",
                                         file_pattern = "_C..txt",
                                         pattern_1 = ".*/",
                                         pattern_2 = "_C..txt")
```
